name: Ceremóniamester
favicon: null
layout_spectrum: 0.85312
typography_spectrum: 0.23032938386313617
title: 'Az esküvőd épp olyan lesz, amilyennek látni szeretnéd'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#003132'
    - '#c4cde8'
    - '#449ec8'
    - '#ac8a83'
    - '#ffa55c'
  brandStrength: 0.8171559064649045
  lightness: 0.9179910253733397
  saturation: 0.5496346454601735
  rhythmicContrast: 0.4911245726980269
purpose: []
